--- 
default: 
  adapter: postgresql
  password: 2211
  pool: "5"
  timeout: 5000
  username: postgres
development: 
  adapter: postgresql
  #database: staticpage_app_development
  password: 2211
  pool: "5"
  timeout: 5000
  username: postgres
production: 
  adapter: postgresql
  #database: staticpage_app_production
  password: 2211
  pool: "5"
  timeout: 5000
  username: postgres
test: 
  adapter: postgresql
  #database: staticpage_app_test
  password: 2211
  pool: "5"
  timeout: 5000
  username: postgres
